### ISSUE TITLE
Bug: Links kept (Not Found or Not Exported) are converted to Internal Links, not preserved as Wikilinks

### ISSUE THREAD

**Issue by joelg** [symunona/obsidian-bulk-exporter#8]
Hi again @symunona,

I've had a chance to more fully test out the new options you implemented to keep links, and I noticed a bug.

It seems that while the new option keeps the links, they are always converted to internal links even when the "Preserve Wiki links" option is selected.

Hopefully that's an easy fix!

Thanks again, really enjoying the plugin.

**Comment by symunona** [comment]
Sorry for that! Thanks for the report! Should be fixed now on 2.0.10 - https://github.com/symunona/obsidian-bulk-exporter/releases/tag/2.0.10

Please do confirm!

(It's been a while since I touched this and I did not remember all the magic it actually does with link replacement, and it was not obvious from the code - now I fixed that too!)
